name: final-project-brook
channels:
  - conda-forge
dependencies:
  - python=3.13.11
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - streamlit
  - altair
  - pydeck
  - bs4
  - fiona
  - gdal
  - ipykernel
  - jupyter
  - plotnine
  - pyogrio
  - scikit-learn
  - seaborn
  - spacy
  - statsmodels
  - vega_datasets
  - pip
  - lxml
  - pip:
      - vl-convert-python
